language: python
python:
    - 2.7
env:
    secure: zq/oGD7oRh8FXAoBXaxy06+ugHyTcycK7MGACeYHHTDIZQLq8ftUMcx7hADPzrNvwxeJj0pLB4k8IicrgavTK7aTvPWKujd10S9RIBsaUCb96g0XKd2N4CvcDeILb5zQ+2GNc48c5d4QeMBS2iThm6Ff5lY6+vqcbDM7Oyhu2U76EoEr5zlijp72LutXFjdJMWQbX2vOd5gwe9TArApwAzEgiEhQD9eFxLi/8n1nbuhLjaSBsewrfkuFeHDUgJTMl0dVD6l7EvL40ePnoZd6itVh8am4pse/UoKBsAecH0kS6IuKdkQ6yez/okHFOXQI8zi1Bc4Sp9aqB++QpOdaGw==
before_install:
    - pip install pep8
install:
    - pip install . --use-mirrors
script:
    - python setup.py nosetests --with-cov --cover-package=PandasRake
    - pep8 --ignore=E501 PandasRake/
    - pep8 --ignore=E501 tests/
notifications:
    email: false
after_success:
    - export HIPCHAT="https://api.hipchat.com/v1/rooms/message?auth_token=${HIPCHAT_TOKEN}&format=json"
    - export SHORT=`echo $COMMIT | cut -c 1-10`
    - export HC_PREFIX="room_id=642430&from=Shippable&message=Decipher#${BUILD_NUMBER}+(${BRANCH}:${SHORT}:python=${PYTHON_VERSION})"
    - curl -d "${HC_PREFIX}+build+passed&color=green" $HIPCHAT
after_failure:
    - export HIPCHAT="https://api.hipchat.com/v1/rooms/message?auth_token=${HIPCHAT_TOKEN}&format=json"
    - export SHORT=`echo $COMMIT | cut -c 1-10`
    - export HC_PREFIX="room_id=642430&from=Shippable&message=Decipher#${BUILD_NUMBER}+(${BRANCH}:${SHORT}:python=${PYTHON_VERSION})"
    - curl -d "${HC_PREFIX}+build+passed&color=green" $HIPCHAT
